### ISSUE TITLE
EZShare lags the computer on large files

### ISSUE THREAD

**Issue by jeffswt** [xmcp/EZShare#1]
EZShare does not work on large files.

On large files, notably those larger than 200MB, the socket pool seems to go down. I hope you could resolve this by replacing reading files in chunks rather than reading in wholes.

This is the exact event log of the error:

```
D:\EZShare>python ezshare.py
[31/Jul/2016:11:31:54] ENGINE Listening for SIGTERM.
[31/Jul/2016:11:31:54] ENGINE Bus STARTING
[31/Jul/2016:11:31:54] ENGINE Set handler for console events.
[31/Jul/2016:11:31:54] ENGINE Started monitor thread '_TimeoutMonitor'.
[31/Jul/2016:11:31:54] ENGINE Serving on http://0.0.0.0
[31/Jul/2016:11:31:54] ENGINE Bus STARTED
127.0.0.1 - - [31/Jul/2016:11:31:56] "GET / HTTP/1.1" 200 1792 "" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:31:56] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 - "http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:31:56] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 - "http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:31:56] "GET /static/bootstrap/js/jquery.min.js HTTP/1.1" 304 - "http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:31:56] "GET /static/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 - "http://localhost/static/bootstrap/css/bootstrap.min.css" "Mozilla/5.0 (Windows NT6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:33:09] "POST /upload HTTP/1.1" 200 22 "http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:33:09] "GET / HTTP/1.1" 200 2099 "" "Mozilla/5.0 (Windows NT 6.3; WOW6; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:33:10] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 122544 "http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:33:10] "GET /static/bootstrap/js/jquery.min.js HTTP/1.1" 200 95962 "http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:33:10] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 36822"http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:33:10] "GET /static/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028 "http://localhost/static/bootstrap/css/bootstrap.min.css" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
127.0.0.1 - - [31/Jul/2016:11:33:12] "GET /download/cb4f3c27b5434f48ad61c2afb19b1644/341.92-quadro-grid-desktop-notebook-win8-win7-64bit-international-whql.exe?force_download=1 HTTP/1.1" 200 215849384 "http://localhost/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
[31/Jul/2016:11:33:14] ENGINE socket.error 10055
Traceback (most recent call last):
  File "C:\Programs\Python3\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 1089, in communicate
    req.respond()
  File "C:\Programs\Python3\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 877, in respond
    self.server.gateway(self).respond()
  File "C:\Programs\Python3\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 1992, in respond
    self.write(chunk)
  File "C:\Programs\Python3\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 2064, in write
    self.req.write(chunk)
  File "C:\Programs\Python3\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 925, in write
    self.conn.wfile.write(chunk)
  File "C:\Programs\Python3\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 1022, in write
    self._flush_unlocked()
  File "C:\Programs\Python3\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 1031, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "C:\Programs\Python3\lib\socket.py", line 593, in write
    return self._sock.send(b)
OSError: [WinError 10055] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full


D:\EZShare>
```

Look forward to solving this issue!

**P.S. This thing happens on `shile` too**

**Comment by xmcp** [comment]
downloading big files is smoothly on my computer (maybe u need more RAM lol)
![image](https://cloud.githubusercontent.com/assets/6646473/17274689/46756958-5720-11e6-860b-25ef4804c3d3.png)

i will try to stream the downloading process and i hope that will solve the issue (as i can't reproduce it).

btw shile project is abandoned and i advise u not to use it anymore due to security vulnerabilities including CSRF.
